### ISSUE TITLE
Need help to understand the code

### ISSUE THREAD

**Issue by trunglebka** [nimaltd/pmeter#1]
Firstly, thank you for sharing the code so that someone with little knowledge like me can learn from it.

I'm reading your code to do my diy and struggling to understand this line https://github.com/nimaltd/pmeter/blob/8ece92b281ed0c78bb1acfd64cc0c8e2a31ffeb5/pmeter.c#L45
I don't understand why we need to configure ARR here. I searched Google, but it wasn't helpful. (as a software engineer, I think the STM32 documentation is terrible :( )

This is not an issue but I don't know where to ask, so please forgive me.

**Comment by nimaltd** [comment]
these 2 lines for set the speed of timer.
```
_PMETER_TIM.Instance->PSC = timer_freq_mhz - 1;
  _PMETER_TIM.Instance->ARR = (uint32_t)((float)_PMETER_SAMPLE / (((float)_PMETER_SAMPLE / 1000.0f) * ((float)_PMETER_SAMPLE / 1000.0f))) - 1;
```

**Comment by trunglebka** [comment]
I've re-read the code and checking the HAL docs (ununderstandable for me :( )
So I consulted ChatGPT (not a trustworthy really, but easy to read), it say:

```
In the context of STM32 microcontrollers and the STM32Cube firmware development package, TIM_HandleTypeDef::Instance::ARR refers to the Auto-Reload Register of a Timer. The Auto-Reload Register determines the period of the timer, i.e., the value at which the timer will reset and generate an update event.

Changing the value of TIM_HandleTypeDef::Instance::ARR allows you to adjust the period of the timer, which, in turn, affects the frequency at which the timer generates interrupts or triggers other actions.
```
Supposed what it say is right, I looked for an update event callback in the code but I can't see it.
Sorry if there is any misinterpretation or my silliness bothers you.

**Comment by nimaltd** [comment]
that timer used for trigger the ADC.
